// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleCourier.Models;

namespace SampleCourier.Models.Migrations
{
    [DbContext(typeof(RoutingSlipSagaDbContext))]
    partial class RoutingSlipSagaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SampleCourier.Models.RoutingSlipState", b =>
                {
                    b.Property<Guid>("CorrelationId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<TimeSpan?>("Duration");

                    b.Property<DateTime?>("EndTime");

                    b.Property<string>("FaultSummary");

                    b.Property<DateTime?>("StartTime");

                    b.Property<string>("State");

                    b.HasKey("CorrelationId");

                    b.ToTable("EfCoreRoutingSlipState");
                });
#pragma warning restore 612, 618
        }
    }
}
